development:
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: testing_chat

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: action-cable-reconnect_production
